package models_secure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*AccountVehicleCreateBody Data to add a vehicle.

swagger:model accountVehicleCreateBody
*/
type AccountVehicleCreateBody struct {

	/* Vehicle license plate. Vehicle has a license plate as a unique identifier.

	Required: true
	Max Length: 8
	Min Length: 4
	Pattern: \A[A-Z0-9]+\z
	*/
	LicensePlate *string `json:"license_plate"`

	/* Vehicle name.

	Required: true
	Max Length: 25
	*/
	Name *string `json:"name"`
}

// Validate validates this account vehicle create body
func (m *AccountVehicleCreateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLicensePlate(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountVehicleCreateBody) validateLicensePlate(formats strfmt.Registry) error {

	if err := validate.Required("license_plate", "body", m.LicensePlate); err != nil {
		return err
	}

	if err := validate.MinLength("license_plate", "body", string(*m.LicensePlate), 4); err != nil {
		return err
	}

	if err := validate.MaxLength("license_plate", "body", string(*m.LicensePlate), 8); err != nil {
		return err
	}

	if err := validate.Pattern("license_plate", "body", string(*m.LicensePlate), `\A[A-Z0-9]+\z`); err != nil {
		return err
	}

	return nil
}

func (m *AccountVehicleCreateBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", string(*m.Name), 25); err != nil {
		return err
	}

	return nil
}
