package models_secure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*AppUpsert422Error app upsert422 error

swagger:model AppUpsert422Error
*/
type AppUpsert422Error struct {

	/* app id
	 */
	AppID ValidationError `json:"app_id,omitempty"`

	/* A list of errors that do not apply to an attribute.
	 */
	Base ValidationError `json:"base,omitempty"`

	/* notification badge
	 */
	NotificationBadge ValidationError `json:"notification_badge,omitempty"`
}

// Validate validates this app upsert422 error
func (m *AppUpsert422Error) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
