package models_secure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*AuthorizationErrorResponse authorization error response

swagger:model authorizationErrorResponse
*/
type AuthorizationErrorResponse struct {

	/* error

	Required: true
	*/
	Error *string `json:"error"`

	/* error description

	Required: true
	*/
	ErrorDescription *string `json:"error_description"`
}

// Validate validates this authorization error response
func (m *AuthorizationErrorResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateError(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateErrorDescription(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthorizationErrorResponse) validateError(formats strfmt.Registry) error {

	if err := validate.Required("error", "body", m.Error); err != nil {
		return err
	}

	return nil
}

func (m *AuthorizationErrorResponse) validateErrorDescription(formats strfmt.Registry) error {

	if err := validate.Required("error_description", "body", m.ErrorDescription); err != nil {
		return err
	}

	return nil
}
