package models_secure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*BaseValidationErrorDetails An error that does not apply to an attribute.

swagger:model baseValidationErrorDetails
*/
type BaseValidationErrorDetails struct {

	/* Error description. Describes an error that does not apply to an attribute.

	Required: true
	*/
	Message *string `json:"message"`

	/* Supplied parameters.

	Required: true
	*/
	Params interface{} `json:"params"`
}

// Validate validates this base validation error details
func (m *BaseValidationErrorDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMessage(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateParams(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BaseValidationErrorDetails) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

func (m *BaseValidationErrorDetails) validateParams(formats strfmt.Registry) error {

	return nil
}
