package models_secure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*CentreLink Link and identifier for a centre.

swagger:model centreLink
*/
type CentreLink struct {

	/* Centre identifier. Identifier to retrieve the centre this deal is related to. Lowercase code name for a specific centre.

	Required: true
	*/
	CentreID *string `json:"centre_id"`

	/* Link to retrieve a centre.

	Required: true
	*/
	Href *string `json:"href"`
}

// Validate validates this centre link
func (m *CentreLink) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCentreID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateHref(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CentreLink) validateCentreID(formats strfmt.Registry) error {

	if err := validate.Required("centre_id", "body", m.CentreID); err != nil {
		return err
	}

	return nil
}

func (m *CentreLink) validateHref(formats strfmt.Registry) error {

	if err := validate.Required("href", "body", m.Href); err != nil {
		return err
	}

	return nil
}
