package models_secure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*CreditCard422Error credit card422 error

swagger:model creditCard422Error
*/
type CreditCard422Error struct {

	/* A list of errors that do not apply to an attribute.
	 */
	Base ValidationError `json:"base,omitempty"`

	/* parent id
	 */
	ParentID ValidationError `json:"parent_id,omitempty"`
}

// Validate validates this credit card422 error
func (m *CreditCard422Error) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
