package models_secure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*EdnaLastLoginLocationInstanceCoordinates Coordinates last logged in from.

swagger:model ednaLastLoginLocationInstanceCoordinates
*/
type EdnaLastLoginLocationInstanceCoordinates struct {

	/* Latitude last logged in from.
	 */
	Lat int64 `json:"lat,omitempty"`

	/* Longitude last logged in from.
	 */
	Lon int64 `json:"lon,omitempty"`
}

// Validate validates this edna last login location instance coordinates
func (m *EdnaLastLoginLocationInstanceCoordinates) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
