package models_secure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*Location Location identifiers and metadata.

swagger:model location
*/
type Location struct {

	/* Level description.

	Required: true
	*/
	LevelDescription *string `json:"level_description"`

	/* Level identifier.

	Required: true
	*/
	LevelID *string `json:"level_id"`

	/* Level name.

	Required: true
	*/
	LevelName *string `json:"level_name"`

	/* Location identifier.

	Required: true
	*/
	LocationID *string `json:"location_id"`

	/* Location name.

	Required: true
	*/
	Name *string `json:"name"`

	/* Primary location. Location is the primary (true) or not primary (false).

	Required: true
	*/
	Primary *bool `json:"primary"`
}

// Validate validates this location
func (m *Location) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLevelDescription(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateLevelID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateLevelName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateLocationID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePrimary(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Location) validateLevelDescription(formats strfmt.Registry) error {

	if err := validate.Required("level_description", "body", m.LevelDescription); err != nil {
		return err
	}

	return nil
}

func (m *Location) validateLevelID(formats strfmt.Registry) error {

	if err := validate.Required("level_id", "body", m.LevelID); err != nil {
		return err
	}

	return nil
}

func (m *Location) validateLevelName(formats strfmt.Registry) error {

	if err := validate.Required("level_name", "body", m.LevelName); err != nil {
		return err
	}

	return nil
}

func (m *Location) validateLocationID(formats strfmt.Registry) error {

	if err := validate.Required("location_id", "body", m.LocationID); err != nil {
		return err
	}

	return nil
}

func (m *Location) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *Location) validatePrimary(formats strfmt.Registry) error {

	if err := validate.Required("primary", "body", m.Primary); err != nil {
		return err
	}

	return nil
}
