package models_secure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Metadata One or more key value pairs describing a specific UUID.

swagger:model metadata
*/
type Metadata interface{}
