package models_secure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*StaffRole staff role

swagger:model staffRole
*/
type StaffRole struct {

	/* Access Attributes

	Required: true
	*/
	AccessAttributes *AccessAttribute `json:"access_attributes"`

	/* type

	Required: true
	*/
	Type *string `json:"type"`
}

// Validate validates this staff role
func (m *StaffRole) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccessAttributes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StaffRole) validateAccessAttributes(formats strfmt.Registry) error {

	if err := validate.Required("access_attributes", "body", m.AccessAttributes); err != nil {
		return err
	}

	if m.AccessAttributes != nil {

		if err := m.AccessAttributes.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}

func (m *StaffRole) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}
