package models_secure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*SwarcoGaragesUpdateBody Data to update a Swarco car park.

swagger:model swarcoGaragesUpdateBody
*/
type SwarcoGaragesUpdateBody struct {

	/* c a r p a r k s

	Required: true
	*/
	CARPARKS *SwarcoCarparksInstance `json:"CARPARKS"`
}

// Validate validates this swarco garages update body
func (m *SwarcoGaragesUpdateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCARPARKS(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SwarcoGaragesUpdateBody) validateCARPARKS(formats strfmt.Registry) error {

	if err := validate.Required("CARPARKS", "body", m.CARPARKS); err != nil {
		return err
	}

	if m.CARPARKS != nil {

		if err := m.CARPARKS.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
