package s_t_o_r_e_t_r_a_d_i_n_g_h_o_u_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStoreTradingHoursParams creates a new GetStoreTradingHoursParams object
// with the default values initialized.
func NewGetStoreTradingHoursParams() *GetStoreTradingHoursParams {
	var ()
	return &GetStoreTradingHoursParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStoreTradingHoursParamsWithTimeout creates a new GetStoreTradingHoursParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStoreTradingHoursParamsWithTimeout(timeout time.Duration) *GetStoreTradingHoursParams {
	var ()
	return &GetStoreTradingHoursParams{

		timeout: timeout,
	}
}

/*GetStoreTradingHoursParams contains all the parameters to send to the API endpoint
for the get store trading hours operation typically these are written to a http.Request
*/
type GetStoreTradingHoursParams struct {

	/*CentreID
	  Centre identifier. Request the store trading-hours with centre_id. Lowercase code name for a specific centre.

	*/
	CentreID string

	timeout time.Duration
}

// WithCentreID adds the centreId to the get store trading hours params
func (o *GetStoreTradingHoursParams) WithCentreID(CentreID string) *GetStoreTradingHoursParams {
	o.CentreID = CentreID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetStoreTradingHoursParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param centre_id
	qrCentreID := o.CentreID
	qCentreID := qrCentreID
	if qCentreID != "" {
		if err := r.SetQueryParam("centre_id", qCentreID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
