package s_t_o_r_e_t_r_a_d_i_n_g_h_o_u_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// NewPostOccasionsParams creates a new PostOccasionsParams object
// with the default values initialized.
func NewPostOccasionsParams() *PostOccasionsParams {
	var ()
	return &PostOccasionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostOccasionsParamsWithTimeout creates a new PostOccasionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostOccasionsParamsWithTimeout(timeout time.Duration) *PostOccasionsParams {
	var ()
	return &PostOccasionsParams{

		timeout: timeout,
	}
}

/*PostOccasionsParams contains all the parameters to send to the API endpoint
for the post occasions operation typically these are written to a http.Request
*/
type PostOccasionsParams struct {

	/*Authorization
	  Staff Access token.

	*/
	Authorization string
	/*OccasionData
	  Data to create an occasion.

	*/
	OccasionData *models_core.OccasionCreateBody

	timeout time.Duration
}

// WithAuthorization adds the authorization to the post occasions params
func (o *PostOccasionsParams) WithAuthorization(Authorization string) *PostOccasionsParams {
	o.Authorization = Authorization
	return o
}

// WithOccasionData adds the occasionData to the post occasions params
func (o *PostOccasionsParams) WithOccasionData(OccasionData *models_core.OccasionCreateBody) *PostOccasionsParams {
	o.OccasionData = OccasionData
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostOccasionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.OccasionData == nil {
		o.OccasionData = new(models_core.OccasionCreateBody)
	}

	if err := r.SetBodyParam(o.OccasionData); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
