package c_e_n_t_r_e_z_o_n_e_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// DeleteCentresZonesZoneIDReader is a Reader for the DeleteCentresZonesZoneID structure.
type DeleteCentresZonesZoneIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteCentresZonesZoneIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteCentresZonesZoneIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteCentresZonesZoneIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteCentresZonesZoneIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCentresZonesZoneIDNoContent creates a DeleteCentresZonesZoneIDNoContent with default headers values
func NewDeleteCentresZonesZoneIDNoContent() *DeleteCentresZonesZoneIDNoContent {
	return &DeleteCentresZonesZoneIDNoContent{}
}

/*DeleteCentresZonesZoneIDNoContent handles this case with default header values.

Successfully deleted the centre zone.
*/
type DeleteCentresZonesZoneIDNoContent struct {
}

func (o *DeleteCentresZonesZoneIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /centres/zones/{zone_id}][%d] deleteCentresZonesZoneIdNoContent ", 204)
}

func (o *DeleteCentresZonesZoneIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCentresZonesZoneIDUnauthorized creates a DeleteCentresZonesZoneIDUnauthorized with default headers values
func NewDeleteCentresZonesZoneIDUnauthorized() *DeleteCentresZonesZoneIDUnauthorized {
	return &DeleteCentresZonesZoneIDUnauthorized{}
}

/*DeleteCentresZonesZoneIDUnauthorized handles this case with default header values.

Unauthorized request.
*/
type DeleteCentresZonesZoneIDUnauthorized struct {
	Payload *models_core.Http401Response
}

func (o *DeleteCentresZonesZoneIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /centres/zones/{zone_id}][%d] deleteCentresZonesZoneIdUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteCentresZonesZoneIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_core.Http401Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCentresZonesZoneIDNotFound creates a DeleteCentresZonesZoneIDNotFound with default headers values
func NewDeleteCentresZonesZoneIDNotFound() *DeleteCentresZonesZoneIDNotFound {
	return &DeleteCentresZonesZoneIDNotFound{}
}

/*DeleteCentresZonesZoneIDNotFound handles this case with default header values.

Zone not found.
*/
type DeleteCentresZonesZoneIDNotFound struct {
	Payload *models_core.Http404Response
}

func (o *DeleteCentresZonesZoneIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /centres/zones/{zone_id}][%d] deleteCentresZonesZoneIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteCentresZonesZoneIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_core.Http404Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
