package c_e_n_t_r_e_z_o_n_e_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// GetCentresZonesZoneIDReader is a Reader for the GetCentresZonesZoneID structure.
type GetCentresZonesZoneIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetCentresZonesZoneIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCentresZonesZoneIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetCentresZonesZoneIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCentresZonesZoneIDOK creates a GetCentresZonesZoneIDOK with default headers values
func NewGetCentresZonesZoneIDOK() *GetCentresZonesZoneIDOK {
	return &GetCentresZonesZoneIDOK{}
}

/*GetCentresZonesZoneIDOK handles this case with default header values.

Successfully retrieved the individual centre zone.
*/
type GetCentresZonesZoneIDOK struct {
	Payload *models_core.ZoneResponse
}

func (o *GetCentresZonesZoneIDOK) Error() string {
	return fmt.Sprintf("[GET /centres/zones/{zone_id}][%d] getCentresZonesZoneIdOK  %+v", 200, o.Payload)
}

func (o *GetCentresZonesZoneIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_core.ZoneResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCentresZonesZoneIDNotFound creates a GetCentresZonesZoneIDNotFound with default headers values
func NewGetCentresZonesZoneIDNotFound() *GetCentresZonesZoneIDNotFound {
	return &GetCentresZonesZoneIDNotFound{}
}

/*GetCentresZonesZoneIDNotFound handles this case with default header values.

Zone not found.
*/
type GetCentresZonesZoneIDNotFound struct {
	Payload *models_core.Http404Response
}

func (o *GetCentresZonesZoneIDNotFound) Error() string {
	return fmt.Sprintf("[GET /centres/zones/{zone_id}][%d] getCentresZonesZoneIdNotFound  %+v", 404, o.Payload)
}

func (o *GetCentresZonesZoneIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_core.Http404Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
