package c_e_n_t_r_e_z_o_n_e_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// NewPatchCentresZonesZoneIDParams creates a new PatchCentresZonesZoneIDParams object
// with the default values initialized.
func NewPatchCentresZonesZoneIDParams() *PatchCentresZonesZoneIDParams {
	var ()
	return &PatchCentresZonesZoneIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchCentresZonesZoneIDParamsWithTimeout creates a new PatchCentresZonesZoneIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchCentresZonesZoneIDParamsWithTimeout(timeout time.Duration) *PatchCentresZonesZoneIDParams {
	var ()
	return &PatchCentresZonesZoneIDParams{

		timeout: timeout,
	}
}

/*PatchCentresZonesZoneIDParams contains all the parameters to send to the API endpoint
for the patch centres zones zone ID operation typically these are written to a http.Request
*/
type PatchCentresZonesZoneIDParams struct {

	/*Authorization
	  Staff Access token.

	*/
	Authorization string
	/*ZoneData
	  Data to update a centre zone.

	*/
	ZoneData *models_core.ZoneUpdateBody
	/*ZoneID
	  Zone identifier. Request the centrezone with zone_id.

	*/
	ZoneID int64

	timeout time.Duration
}

// WithAuthorization adds the authorization to the patch centres zones zone ID params
func (o *PatchCentresZonesZoneIDParams) WithAuthorization(Authorization string) *PatchCentresZonesZoneIDParams {
	o.Authorization = Authorization
	return o
}

// WithZoneData adds the zoneData to the patch centres zones zone ID params
func (o *PatchCentresZonesZoneIDParams) WithZoneData(ZoneData *models_core.ZoneUpdateBody) *PatchCentresZonesZoneIDParams {
	o.ZoneData = ZoneData
	return o
}

// WithZoneID adds the zoneId to the patch centres zones zone ID params
func (o *PatchCentresZonesZoneIDParams) WithZoneID(ZoneID int64) *PatchCentresZonesZoneIDParams {
	o.ZoneID = ZoneID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PatchCentresZonesZoneIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.ZoneData == nil {
		o.ZoneData = new(models_core.ZoneUpdateBody)
	}

	if err := r.SetBodyParam(o.ZoneData); err != nil {
		return err
	}

	// path param zone_id
	if err := r.SetPathParam("zone_id", swag.FormatInt64(o.ZoneID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
