package c_e_n_t_r_e_z_o_n_e_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// NewPostCentresZonesParams creates a new PostCentresZonesParams object
// with the default values initialized.
func NewPostCentresZonesParams() *PostCentresZonesParams {
	var ()
	return &PostCentresZonesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostCentresZonesParamsWithTimeout creates a new PostCentresZonesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostCentresZonesParamsWithTimeout(timeout time.Duration) *PostCentresZonesParams {
	var ()
	return &PostCentresZonesParams{

		timeout: timeout,
	}
}

/*PostCentresZonesParams contains all the parameters to send to the API endpoint
for the post centres zones operation typically these are written to a http.Request
*/
type PostCentresZonesParams struct {

	/*Authorization
	  Staff Access token.

	*/
	Authorization string
	/*ZoneData
	  Data to create centre zones.

	*/
	ZoneData *models_core.ZoneCreateBody

	timeout time.Duration
}

// WithAuthorization adds the authorization to the post centres zones params
func (o *PostCentresZonesParams) WithAuthorization(Authorization string) *PostCentresZonesParams {
	o.Authorization = Authorization
	return o
}

// WithZoneData adds the zoneData to the post centres zones params
func (o *PostCentresZonesParams) WithZoneData(ZoneData *models_core.ZoneCreateBody) *PostCentresZonesParams {
	o.ZoneData = ZoneData
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostCentresZonesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.ZoneData == nil {
		o.ZoneData = new(models_core.ZoneCreateBody)
	}

	if err := r.SetBodyParam(o.ZoneData); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
