package p_e_o_p_l_e_m_a_n_a_g_e_m_e_n_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_secure"
)

// NewPostPeoplePersonIDParkingRefundParams creates a new PostPeoplePersonIDParkingRefundParams object
// with the default values initialized.
func NewPostPeoplePersonIDParkingRefundParams() *PostPeoplePersonIDParkingRefundParams {
	var ()
	return &PostPeoplePersonIDParkingRefundParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostPeoplePersonIDParkingRefundParamsWithTimeout creates a new PostPeoplePersonIDParkingRefundParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostPeoplePersonIDParkingRefundParamsWithTimeout(timeout time.Duration) *PostPeoplePersonIDParkingRefundParams {
	var ()
	return &PostPeoplePersonIDParkingRefundParams{

		timeout: timeout,
	}
}

/*PostPeoplePersonIDParkingRefundParams contains all the parameters to send to the API endpoint
for the post people person ID parking refund operation typically these are written to a http.Request
*/
type PostPeoplePersonIDParkingRefundParams struct {

	/*Authorization
	  Staff access token

	*/
	Authorization string
	/*Data
	  Data to refund the parking session.

	*/
	Data *models_secure.ParkingRefundBody
	/*PersonID
	  Identifier of the account

	*/
	PersonID string

	timeout time.Duration
}

// WithAuthorization adds the authorization to the post people person ID parking refund params
func (o *PostPeoplePersonIDParkingRefundParams) WithAuthorization(Authorization string) *PostPeoplePersonIDParkingRefundParams {
	o.Authorization = Authorization
	return o
}

// WithData adds the data to the post people person ID parking refund params
func (o *PostPeoplePersonIDParkingRefundParams) WithData(Data *models_secure.ParkingRefundBody) *PostPeoplePersonIDParkingRefundParams {
	o.Data = Data
	return o
}

// WithPersonID adds the personId to the post people person ID parking refund params
func (o *PostPeoplePersonIDParkingRefundParams) WithPersonID(PersonID string) *PostPeoplePersonIDParkingRefundParams {
	o.PersonID = PersonID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostPeoplePersonIDParkingRefundParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.Data == nil {
		o.Data = new(models_secure.ParkingRefundBody)
	}

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param person_id
	if err := r.SetPathParam("person_id", o.PersonID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
