package p_e_o_p_l_e_m_a_n_a_g_e_m_e_n_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_secure"
)

// PostPeopleNotificationReader is a Reader for the PostPeopleNotification structure.
type PostPeopleNotificationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostPeopleNotificationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPostPeopleNotificationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostPeopleNotificationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewPostPeopleNotificationUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostPeopleNotificationNoContent creates a PostPeopleNotificationNoContent with default headers values
func NewPostPeopleNotificationNoContent() *PostPeopleNotificationNoContent {
	return &PostPeopleNotificationNoContent{}
}

/*PostPeopleNotificationNoContent handles this case with default header values.

Message published succesfully
*/
type PostPeopleNotificationNoContent struct {
}

func (o *PostPeopleNotificationNoContent) Error() string {
	return fmt.Sprintf("[POST /people/notification][%d] postPeopleNotificationNoContent ", 204)
}

func (o *PostPeopleNotificationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostPeopleNotificationBadRequest creates a PostPeopleNotificationBadRequest with default headers values
func NewPostPeopleNotificationBadRequest() *PostPeopleNotificationBadRequest {
	return &PostPeopleNotificationBadRequest{}
}

/*PostPeopleNotificationBadRequest handles this case with default header values.

Bad request
*/
type PostPeopleNotificationBadRequest struct {
	Payload *models_secure.Person400Response
}

func (o *PostPeopleNotificationBadRequest) Error() string {
	return fmt.Sprintf("[POST /people/notification][%d] postPeopleNotificationBadRequest  %+v", 400, o.Payload)
}

func (o *PostPeopleNotificationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.Person400Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostPeopleNotificationUnprocessableEntity creates a PostPeopleNotificationUnprocessableEntity with default headers values
func NewPostPeopleNotificationUnprocessableEntity() *PostPeopleNotificationUnprocessableEntity {
	return &PostPeopleNotificationUnprocessableEntity{}
}

/*PostPeopleNotificationUnprocessableEntity handles this case with default header values.

Centre, Person or category identitifer does not exist
*/
type PostPeopleNotificationUnprocessableEntity struct {
	Payload *models_secure.Notifications422Response
}

func (o *PostPeopleNotificationUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /people/notification][%d] postPeopleNotificationUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *PostPeopleNotificationUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.Notifications422Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
