package c_e_n_t_r_e_t_r_a_d_i_n_g_h_o_u_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCentresCentreIDTradingHoursParams creates a new GetCentresCentreIDTradingHoursParams object
// with the default values initialized.
func NewGetCentresCentreIDTradingHoursParams() *GetCentresCentreIDTradingHoursParams {
	var ()
	return &GetCentresCentreIDTradingHoursParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCentresCentreIDTradingHoursParamsWithTimeout creates a new GetCentresCentreIDTradingHoursParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCentresCentreIDTradingHoursParamsWithTimeout(timeout time.Duration) *GetCentresCentreIDTradingHoursParams {
	var ()
	return &GetCentresCentreIDTradingHoursParams{

		timeout: timeout,
	}
}

/*GetCentresCentreIDTradingHoursParams contains all the parameters to send to the API endpoint
for the get centres centre ID trading hours operation typically these are written to a http.Request
*/
type GetCentresCentreIDTradingHoursParams struct {

	/*CentreID
	  Centre identifier. Request the centre trading-hours with centre_id. Lowercase code name for a specific centre.

	*/
	CentreID string

	timeout time.Duration
}

// WithCentreID adds the centreId to the get centres centre ID trading hours params
func (o *GetCentresCentreIDTradingHoursParams) WithCentreID(CentreID string) *GetCentresCentreIDTradingHoursParams {
	o.CentreID = CentreID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetCentresCentreIDTradingHoursParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param centre_id
	if err := r.SetPathParam("centre_id", o.CentreID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
