package p_a_y_m_e_n_t_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_secure"
)

// NewPatchPaymentsPaymentMethodsPaymentMethodTokenParams creates a new PatchPaymentsPaymentMethodsPaymentMethodTokenParams object
// with the default values initialized.
func NewPatchPaymentsPaymentMethodsPaymentMethodTokenParams() *PatchPaymentsPaymentMethodsPaymentMethodTokenParams {
	var ()
	return &PatchPaymentsPaymentMethodsPaymentMethodTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchPaymentsPaymentMethodsPaymentMethodTokenParamsWithTimeout creates a new PatchPaymentsPaymentMethodsPaymentMethodTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchPaymentsPaymentMethodsPaymentMethodTokenParamsWithTimeout(timeout time.Duration) *PatchPaymentsPaymentMethodsPaymentMethodTokenParams {
	var ()
	return &PatchPaymentsPaymentMethodsPaymentMethodTokenParams{

		timeout: timeout,
	}
}

/*PatchPaymentsPaymentMethodsPaymentMethodTokenParams contains all the parameters to send to the API endpoint
for the patch payments payment methods payment method token operation typically these are written to a http.Request
*/
type PatchPaymentsPaymentMethodsPaymentMethodTokenParams struct {

	/*PaymentMethodData
	  Data to update the details associated with a payment method.

	*/
	PaymentMethodData *models_secure.PaymentMethodUpdateBody
	/*PaymentMethodToken
	  Payment method token.

	*/
	PaymentMethodToken string

	timeout time.Duration
}

// WithPaymentMethodData adds the paymentMethodData to the patch payments payment methods payment method token params
func (o *PatchPaymentsPaymentMethodsPaymentMethodTokenParams) WithPaymentMethodData(PaymentMethodData *models_secure.PaymentMethodUpdateBody) *PatchPaymentsPaymentMethodsPaymentMethodTokenParams {
	o.PaymentMethodData = PaymentMethodData
	return o
}

// WithPaymentMethodToken adds the paymentMethodToken to the patch payments payment methods payment method token params
func (o *PatchPaymentsPaymentMethodsPaymentMethodTokenParams) WithPaymentMethodToken(PaymentMethodToken string) *PatchPaymentsPaymentMethodsPaymentMethodTokenParams {
	o.PaymentMethodToken = PaymentMethodToken
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PatchPaymentsPaymentMethodsPaymentMethodTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.PaymentMethodData == nil {
		o.PaymentMethodData = new(models_secure.PaymentMethodUpdateBody)
	}

	if err := r.SetBodyParam(o.PaymentMethodData); err != nil {
		return err
	}

	// path param payment_method_token
	if err := r.SetPathParam("payment_method_token", o.PaymentMethodToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
