package p_a_y_m_e_n_t_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_secure"
)

// PostPaymentsTransactionsTransactionIDCaptureReader is a Reader for the PostPaymentsTransactionsTransactionIDCapture structure.
type PostPaymentsTransactionsTransactionIDCaptureReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostPaymentsTransactionsTransactionIDCaptureReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostPaymentsTransactionsTransactionIDCaptureOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 422:
		result := NewPostPaymentsTransactionsTransactionIDCaptureUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostPaymentsTransactionsTransactionIDCaptureOK creates a PostPaymentsTransactionsTransactionIDCaptureOK with default headers values
func NewPostPaymentsTransactionsTransactionIDCaptureOK() *PostPaymentsTransactionsTransactionIDCaptureOK {
	return &PostPaymentsTransactionsTransactionIDCaptureOK{}
}

/*PostPaymentsTransactionsTransactionIDCaptureOK handles this case with default header values.

Capture request processed with success
*/
type PostPaymentsTransactionsTransactionIDCaptureOK struct {
	Payload *models_secure.TransactionCaptureResponse
}

func (o *PostPaymentsTransactionsTransactionIDCaptureOK) Error() string {
	return fmt.Sprintf("[POST /payments/transactions/{transaction_id}/capture][%d] postPaymentsTransactionsTransactionIdCaptureOK  %+v", 200, o.Payload)
}

func (o *PostPaymentsTransactionsTransactionIDCaptureOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.TransactionCaptureResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostPaymentsTransactionsTransactionIDCaptureUnprocessableEntity creates a PostPaymentsTransactionsTransactionIDCaptureUnprocessableEntity with default headers values
func NewPostPaymentsTransactionsTransactionIDCaptureUnprocessableEntity() *PostPaymentsTransactionsTransactionIDCaptureUnprocessableEntity {
	return &PostPaymentsTransactionsTransactionIDCaptureUnprocessableEntity{}
}

/*PostPaymentsTransactionsTransactionIDCaptureUnprocessableEntity handles this case with default header values.

Transaction not processed. Returns an array of error messages explaining the problems with the provided attributes.
*/
type PostPaymentsTransactionsTransactionIDCaptureUnprocessableEntity struct {
	Payload *models_secure.Payment422Response
}

func (o *PostPaymentsTransactionsTransactionIDCaptureUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /payments/transactions/{transaction_id}/capture][%d] postPaymentsTransactionsTransactionIdCaptureUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *PostPaymentsTransactionsTransactionIDCaptureUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.Payment422Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
