package c_a_t_e_g_o_r_i_e_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCategoriesCategoryIDParams creates a new DeleteCategoriesCategoryIDParams object
// with the default values initialized.
func NewDeleteCategoriesCategoryIDParams() *DeleteCategoriesCategoryIDParams {
	var ()
	return &DeleteCategoriesCategoryIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCategoriesCategoryIDParamsWithTimeout creates a new DeleteCategoriesCategoryIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCategoriesCategoryIDParamsWithTimeout(timeout time.Duration) *DeleteCategoriesCategoryIDParams {
	var ()
	return &DeleteCategoriesCategoryIDParams{

		timeout: timeout,
	}
}

/*DeleteCategoriesCategoryIDParams contains all the parameters to send to the API endpoint
for the delete categories category ID operation typically these are written to a http.Request
*/
type DeleteCategoriesCategoryIDParams struct {

	/*Authorization
	  Staff Access token.

	*/
	Authorization string
	/*CategoryID
	  Category identifier. Request to delete the category with category_id.

	*/
	CategoryID int64

	timeout time.Duration
}

// WithAuthorization adds the authorization to the delete categories category ID params
func (o *DeleteCategoriesCategoryIDParams) WithAuthorization(Authorization string) *DeleteCategoriesCategoryIDParams {
	o.Authorization = Authorization
	return o
}

// WithCategoryID adds the categoryId to the delete categories category ID params
func (o *DeleteCategoriesCategoryIDParams) WithCategoryID(CategoryID int64) *DeleteCategoriesCategoryIDParams {
	o.CategoryID = CategoryID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCategoriesCategoryIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param category_id
	if err := r.SetPathParam("category_id", swag.FormatInt64(o.CategoryID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
