package c_a_t_e_g_o_r_i_e_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// PatchCategoriesGroupsGroupIDReader is a Reader for the PatchCategoriesGroupsGroupID structure.
type PatchCategoriesGroupsGroupIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PatchCategoriesGroupsGroupIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPatchCategoriesGroupsGroupIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPatchCategoriesGroupsGroupIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPatchCategoriesGroupsGroupIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewPatchCategoriesGroupsGroupIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchCategoriesGroupsGroupIDNoContent creates a PatchCategoriesGroupsGroupIDNoContent with default headers values
func NewPatchCategoriesGroupsGroupIDNoContent() *PatchCategoriesGroupsGroupIDNoContent {
	return &PatchCategoriesGroupsGroupIDNoContent{}
}

/*PatchCategoriesGroupsGroupIDNoContent handles this case with default header values.

Successfully updated the group.
*/
type PatchCategoriesGroupsGroupIDNoContent struct {
}

func (o *PatchCategoriesGroupsGroupIDNoContent) Error() string {
	return fmt.Sprintf("[PATCH /categories/groups/{group_id}][%d] patchCategoriesGroupsGroupIdNoContent ", 204)
}

func (o *PatchCategoriesGroupsGroupIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchCategoriesGroupsGroupIDUnauthorized creates a PatchCategoriesGroupsGroupIDUnauthorized with default headers values
func NewPatchCategoriesGroupsGroupIDUnauthorized() *PatchCategoriesGroupsGroupIDUnauthorized {
	return &PatchCategoriesGroupsGroupIDUnauthorized{}
}

/*PatchCategoriesGroupsGroupIDUnauthorized handles this case with default header values.

Unauthorized request.
*/
type PatchCategoriesGroupsGroupIDUnauthorized struct {
	Payload *models_core.Http401Response
}

func (o *PatchCategoriesGroupsGroupIDUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /categories/groups/{group_id}][%d] patchCategoriesGroupsGroupIdUnauthorized  %+v", 401, o.Payload)
}

func (o *PatchCategoriesGroupsGroupIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_core.Http401Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchCategoriesGroupsGroupIDNotFound creates a PatchCategoriesGroupsGroupIDNotFound with default headers values
func NewPatchCategoriesGroupsGroupIDNotFound() *PatchCategoriesGroupsGroupIDNotFound {
	return &PatchCategoriesGroupsGroupIDNotFound{}
}

/*PatchCategoriesGroupsGroupIDNotFound handles this case with default header values.

Group not found.
*/
type PatchCategoriesGroupsGroupIDNotFound struct {
	Payload *models_core.Http404Response
}

func (o *PatchCategoriesGroupsGroupIDNotFound) Error() string {
	return fmt.Sprintf("[PATCH /categories/groups/{group_id}][%d] patchCategoriesGroupsGroupIdNotFound  %+v", 404, o.Payload)
}

func (o *PatchCategoriesGroupsGroupIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_core.Http404Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchCategoriesGroupsGroupIDUnprocessableEntity creates a PatchCategoriesGroupsGroupIDUnprocessableEntity with default headers values
func NewPatchCategoriesGroupsGroupIDUnprocessableEntity() *PatchCategoriesGroupsGroupIDUnprocessableEntity {
	return &PatchCategoriesGroupsGroupIDUnprocessableEntity{}
}

/*PatchCategoriesGroupsGroupIDUnprocessableEntity handles this case with default header values.

Group not created. Returns an array of error messages explaining the problems with the provided attributes.
*/
type PatchCategoriesGroupsGroupIDUnprocessableEntity struct {
	Payload *models_core.Group422Response
}

func (o *PatchCategoriesGroupsGroupIDUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PATCH /categories/groups/{group_id}][%d] patchCategoriesGroupsGroupIdUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *PatchCategoriesGroupsGroupIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_core.Group422Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
