package w_i_s_h_l_i_s_t_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteFavoritesItemsKindResourceIDParams creates a new DeleteFavoritesItemsKindResourceIDParams object
// with the default values initialized.
func NewDeleteFavoritesItemsKindResourceIDParams() *DeleteFavoritesItemsKindResourceIDParams {
	var ()
	return &DeleteFavoritesItemsKindResourceIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFavoritesItemsKindResourceIDParamsWithTimeout creates a new DeleteFavoritesItemsKindResourceIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFavoritesItemsKindResourceIDParamsWithTimeout(timeout time.Duration) *DeleteFavoritesItemsKindResourceIDParams {
	var ()
	return &DeleteFavoritesItemsKindResourceIDParams{

		timeout: timeout,
	}
}

/*DeleteFavoritesItemsKindResourceIDParams contains all the parameters to send to the API endpoint
for the delete favorites items kind resource ID operation typically these are written to a http.Request
*/
type DeleteFavoritesItemsKindResourceIDParams struct {

	/*Authorization
	  Access token

	*/
	Authorization string
	/*Kind
	  Wishlist item's external resource kind.

	*/
	Kind string
	/*ResourceID
	  Wishlist item's external resource identifier.

	*/
	ResourceID string

	timeout time.Duration
}

// WithAuthorization adds the authorization to the delete favorites items kind resource ID params
func (o *DeleteFavoritesItemsKindResourceIDParams) WithAuthorization(Authorization string) *DeleteFavoritesItemsKindResourceIDParams {
	o.Authorization = Authorization
	return o
}

// WithKind adds the kind to the delete favorites items kind resource ID params
func (o *DeleteFavoritesItemsKindResourceIDParams) WithKind(Kind string) *DeleteFavoritesItemsKindResourceIDParams {
	o.Kind = Kind
	return o
}

// WithResourceID adds the resourceId to the delete favorites items kind resource ID params
func (o *DeleteFavoritesItemsKindResourceIDParams) WithResourceID(ResourceID string) *DeleteFavoritesItemsKindResourceIDParams {
	o.ResourceID = ResourceID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFavoritesItemsKindResourceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param kind
	if err := r.SetPathParam("kind", o.Kind); err != nil {
		return err
	}

	// path param resource_id
	if err := r.SetPathParam("resource_id", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
