package w_i_s_h_l_i_s_t_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_secure"
)

// DeleteFavoritesItemsKindResourceIDReader is a Reader for the DeleteFavoritesItemsKindResourceID structure.
type DeleteFavoritesItemsKindResourceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteFavoritesItemsKindResourceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteFavoritesItemsKindResourceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteFavoritesItemsKindResourceIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteFavoritesItemsKindResourceIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteFavoritesItemsKindResourceIDOK creates a DeleteFavoritesItemsKindResourceIDOK with default headers values
func NewDeleteFavoritesItemsKindResourceIDOK() *DeleteFavoritesItemsKindResourceIDOK {
	return &DeleteFavoritesItemsKindResourceIDOK{}
}

/*DeleteFavoritesItemsKindResourceIDOK handles this case with default header values.

Successfully deleted the wishlist item.
*/
type DeleteFavoritesItemsKindResourceIDOK struct {
	Payload *models_secure.WishlistItemResponse
}

func (o *DeleteFavoritesItemsKindResourceIDOK) Error() string {
	return fmt.Sprintf("[DELETE /favorites/items/{kind}/{resource_id}][%d] deleteFavoritesItemsKindResourceIdOK  %+v", 200, o.Payload)
}

func (o *DeleteFavoritesItemsKindResourceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.WishlistItemResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteFavoritesItemsKindResourceIDUnauthorized creates a DeleteFavoritesItemsKindResourceIDUnauthorized with default headers values
func NewDeleteFavoritesItemsKindResourceIDUnauthorized() *DeleteFavoritesItemsKindResourceIDUnauthorized {
	return &DeleteFavoritesItemsKindResourceIDUnauthorized{}
}

/*DeleteFavoritesItemsKindResourceIDUnauthorized handles this case with default header values.

Unauthorized request
*/
type DeleteFavoritesItemsKindResourceIDUnauthorized struct {
	Payload *models_secure.UnauthorizedResponse
}

func (o *DeleteFavoritesItemsKindResourceIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /favorites/items/{kind}/{resource_id}][%d] deleteFavoritesItemsKindResourceIdUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteFavoritesItemsKindResourceIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.UnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteFavoritesItemsKindResourceIDNotFound creates a DeleteFavoritesItemsKindResourceIDNotFound with default headers values
func NewDeleteFavoritesItemsKindResourceIDNotFound() *DeleteFavoritesItemsKindResourceIDNotFound {
	return &DeleteFavoritesItemsKindResourceIDNotFound{}
}

/*DeleteFavoritesItemsKindResourceIDNotFound handles this case with default header values.

Resource not found.
*/
type DeleteFavoritesItemsKindResourceIDNotFound struct {
	Payload *models_secure.Http404Response
}

func (o *DeleteFavoritesItemsKindResourceIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /favorites/items/{kind}/{resource_id}][%d] deleteFavoritesItemsKindResourceIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteFavoritesItemsKindResourceIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.Http404Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
