package w_i_s_h_l_i_s_t_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_secure"
)

// PostFavoritesItemsReader is a Reader for the PostFavoritesItems structure.
type PostFavoritesItemsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostFavoritesItemsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostFavoritesItemsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewPostFavoritesItemsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostFavoritesItemsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostFavoritesItemsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewPostFavoritesItemsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostFavoritesItemsOK creates a PostFavoritesItemsOK with default headers values
func NewPostFavoritesItemsOK() *PostFavoritesItemsOK {
	return &PostFavoritesItemsOK{}
}

/*PostFavoritesItemsOK handles this case with default header values.

Wishlist item already created.
*/
type PostFavoritesItemsOK struct {
	Payload *models_secure.WishlistItemResponse
}

func (o *PostFavoritesItemsOK) Error() string {
	return fmt.Sprintf("[POST /favorites/items][%d] postFavoritesItemsOK  %+v", 200, o.Payload)
}

func (o *PostFavoritesItemsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.WishlistItemResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostFavoritesItemsCreated creates a PostFavoritesItemsCreated with default headers values
func NewPostFavoritesItemsCreated() *PostFavoritesItemsCreated {
	return &PostFavoritesItemsCreated{}
}

/*PostFavoritesItemsCreated handles this case with default header values.

Successfully created the wishlist item.
*/
type PostFavoritesItemsCreated struct {
	Payload *models_secure.WishlistItemResponse
}

func (o *PostFavoritesItemsCreated) Error() string {
	return fmt.Sprintf("[POST /favorites/items][%d] postFavoritesItemsCreated  %+v", 201, o.Payload)
}

func (o *PostFavoritesItemsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.WishlistItemResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostFavoritesItemsUnauthorized creates a PostFavoritesItemsUnauthorized with default headers values
func NewPostFavoritesItemsUnauthorized() *PostFavoritesItemsUnauthorized {
	return &PostFavoritesItemsUnauthorized{}
}

/*PostFavoritesItemsUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostFavoritesItemsUnauthorized struct {
	Payload *models_secure.UnauthorizedResponse
}

func (o *PostFavoritesItemsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /favorites/items][%d] postFavoritesItemsUnauthorized  %+v", 401, o.Payload)
}

func (o *PostFavoritesItemsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.UnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostFavoritesItemsNotFound creates a PostFavoritesItemsNotFound with default headers values
func NewPostFavoritesItemsNotFound() *PostFavoritesItemsNotFound {
	return &PostFavoritesItemsNotFound{}
}

/*PostFavoritesItemsNotFound handles this case with default header values.

Resource not found
*/
type PostFavoritesItemsNotFound struct {
	Payload *models_secure.Http404Response
}

func (o *PostFavoritesItemsNotFound) Error() string {
	return fmt.Sprintf("[POST /favorites/items][%d] postFavoritesItemsNotFound  %+v", 404, o.Payload)
}

func (o *PostFavoritesItemsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.Http404Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostFavoritesItemsUnprocessableEntity creates a PostFavoritesItemsUnprocessableEntity with default headers values
func NewPostFavoritesItemsUnprocessableEntity() *PostFavoritesItemsUnprocessableEntity {
	return &PostFavoritesItemsUnprocessableEntity{}
}

/*PostFavoritesItemsUnprocessableEntity handles this case with default header values.

Wishlist item not created. Returns an array of error messages explaining the problems with the provided attributes.
*/
type PostFavoritesItemsUnprocessableEntity struct {
	Payload *models_secure.WishlistItem422Response
}

func (o *PostFavoritesItemsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /favorites/items][%d] postFavoritesItemsUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *PostFavoritesItemsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.WishlistItem422Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
