package c_e_n_t_r_e_p_a_r_k_i_n_g_r_a_t_e_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// GetCentresParkingsReader is a Reader for the GetCentresParkings structure.
type GetCentresParkingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetCentresParkingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCentresParkingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCentresParkingsOK creates a GetCentresParkingsOK with default headers values
func NewGetCentresParkingsOK() *GetCentresParkingsOK {
	return &GetCentresParkingsOK{}
}

/*GetCentresParkingsOK handles this case with default header values.

Successfully retrieved the list of centre parking rates.
*/
type GetCentresParkingsOK struct {
	/*URI of created parking.
	 */
	Location string

	Payload *models_core.ParkingListResponse
}

func (o *GetCentresParkingsOK) Error() string {
	return fmt.Sprintf("[GET /centres/parkings][%d] getCentresParkingsOK  %+v", 200, o.Payload)
}

func (o *GetCentresParkingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header location
	o.Location = response.GetHeader("location")

	o.Payload = new(models_core.ParkingListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
