package c_u_r_a_t_i_o_n_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// DeleteCurationsCurationIDReader is a Reader for the DeleteCurationsCurationID structure.
type DeleteCurationsCurationIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteCurationsCurationIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteCurationsCurationIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteCurationsCurationIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteCurationsCurationIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCurationsCurationIDNoContent creates a DeleteCurationsCurationIDNoContent with default headers values
func NewDeleteCurationsCurationIDNoContent() *DeleteCurationsCurationIDNoContent {
	return &DeleteCurationsCurationIDNoContent{}
}

/*DeleteCurationsCurationIDNoContent handles this case with default header values.

Successfully deleted the curation.
*/
type DeleteCurationsCurationIDNoContent struct {
}

func (o *DeleteCurationsCurationIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /curations/{curation_id}][%d] deleteCurationsCurationIdNoContent ", 204)
}

func (o *DeleteCurationsCurationIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCurationsCurationIDUnauthorized creates a DeleteCurationsCurationIDUnauthorized with default headers values
func NewDeleteCurationsCurationIDUnauthorized() *DeleteCurationsCurationIDUnauthorized {
	return &DeleteCurationsCurationIDUnauthorized{}
}

/*DeleteCurationsCurationIDUnauthorized handles this case with default header values.

Unauthorized request.
*/
type DeleteCurationsCurationIDUnauthorized struct {
	Payload *models_core.Http401Response
}

func (o *DeleteCurationsCurationIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /curations/{curation_id}][%d] deleteCurationsCurationIdUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteCurationsCurationIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_core.Http401Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCurationsCurationIDNotFound creates a DeleteCurationsCurationIDNotFound with default headers values
func NewDeleteCurationsCurationIDNotFound() *DeleteCurationsCurationIDNotFound {
	return &DeleteCurationsCurationIDNotFound{}
}

/*DeleteCurationsCurationIDNotFound handles this case with default header values.

Curation not found.
*/
type DeleteCurationsCurationIDNotFound struct {
	Payload *models_core.Http404Response
}

func (o *DeleteCurationsCurationIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /curations/{curation_id}][%d] deleteCurationsCurationIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteCurationsCurationIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_core.Http404Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
