package s_e_a_r_c_h

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// GetSearchStoresReader is a Reader for the GetSearchStores structure.
type GetSearchStoresReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetSearchStoresReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSearchStoresOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSearchStoresOK creates a GetSearchStoresOK with default headers values
func NewGetSearchStoresOK() *GetSearchStoresOK {
	return &GetSearchStoresOK{}
}

/*GetSearchStoresOK handles this case with default header values.

Successfully retrieved the search results.
*/
type GetSearchStoresOK struct {
	Payload *models_core.SearchStoreResponse
}

func (o *GetSearchStoresOK) Error() string {
	return fmt.Sprintf("[GET /search/stores][%d] getSearchStoresOK  %+v", 200, o.Payload)
}

func (o *GetSearchStoresOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_core.SearchStoreResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
