package d_e_a_l_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDealsDealIDParams creates a new DeleteDealsDealIDParams object
// with the default values initialized.
func NewDeleteDealsDealIDParams() *DeleteDealsDealIDParams {
	var ()
	return &DeleteDealsDealIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDealsDealIDParamsWithTimeout creates a new DeleteDealsDealIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDealsDealIDParamsWithTimeout(timeout time.Duration) *DeleteDealsDealIDParams {
	var ()
	return &DeleteDealsDealIDParams{

		timeout: timeout,
	}
}

/*DeleteDealsDealIDParams contains all the parameters to send to the API endpoint
for the delete deals deal ID operation typically these are written to a http.Request
*/
type DeleteDealsDealIDParams struct {

	/*Authorization
	  Staff Access token.

	*/
	Authorization string
	/*DealID
	  Deal identifier. Request to delete the deal with deal_id.

	*/
	DealID int64

	timeout time.Duration
}

// WithAuthorization adds the authorization to the delete deals deal ID params
func (o *DeleteDealsDealIDParams) WithAuthorization(Authorization string) *DeleteDealsDealIDParams {
	o.Authorization = Authorization
	return o
}

// WithDealID adds the dealId to the delete deals deal ID params
func (o *DeleteDealsDealIDParams) WithDealID(DealID int64) *DeleteDealsDealIDParams {
	o.DealID = DealID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDealsDealIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param deal_id
	if err := r.SetPathParam("deal_id", swag.FormatInt64(o.DealID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
