package d_e_a_l_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// GetDealsReader is a Reader for the GetDeals structure.
type GetDealsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetDealsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDealsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDealsOK creates a GetDealsOK with default headers values
func NewGetDealsOK() *GetDealsOK {
	return &GetDealsOK{}
}

/*GetDealsOK handles this case with default header values.

Successfully retrieved the list of deals.
*/
type GetDealsOK struct {
	Payload *models_core.DealsListResponse
}

func (o *GetDealsOK) Error() string {
	return fmt.Sprintf("[GET /deals][%d] getDealsOK  %+v", 200, o.Payload)
}

func (o *GetDealsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_core.DealsListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
