package d_e_a_l_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// NewPostDealsParams creates a new PostDealsParams object
// with the default values initialized.
func NewPostDealsParams() *PostDealsParams {
	var ()
	return &PostDealsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDealsParamsWithTimeout creates a new PostDealsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDealsParamsWithTimeout(timeout time.Duration) *PostDealsParams {
	var ()
	return &PostDealsParams{

		timeout: timeout,
	}
}

/*PostDealsParams contains all the parameters to send to the API endpoint
for the post deals operation typically these are written to a http.Request
*/
type PostDealsParams struct {

	/*Authorization
	  Staff Access token.

	*/
	Authorization string
	/*DealData
	  Data to create a deal.

	*/
	DealData *models_core.DealCreateBody

	timeout time.Duration
}

// WithAuthorization adds the authorization to the post deals params
func (o *PostDealsParams) WithAuthorization(Authorization string) *PostDealsParams {
	o.Authorization = Authorization
	return o
}

// WithDealData adds the dealData to the post deals params
func (o *PostDealsParams) WithDealData(DealData *models_core.DealCreateBody) *PostDealsParams {
	o.DealData = DealData
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostDealsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.DealData == nil {
		o.DealData = new(models_core.DealCreateBody)
	}

	if err := r.SetBodyParam(o.DealData); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
