package s_t_a_f_f_m_a_n_a_g_e_m_e_n_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_secure"
)

// PostStaffReader is a Reader for the PostStaff structure.
type PostStaffReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostStaffReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostStaffCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostStaffUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostStaffCreated creates a PostStaffCreated with default headers values
func NewPostStaffCreated() *PostStaffCreated {
	return &PostStaffCreated{}
}

/*PostStaffCreated handles this case with default header values.

Return successfully created staff.
*/
type PostStaffCreated struct {
	Payload *models_secure.Staff
}

func (o *PostStaffCreated) Error() string {
	return fmt.Sprintf("[POST /staff][%d] postStaffCreated  %+v", 201, o.Payload)
}

func (o *PostStaffCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.Staff)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostStaffUnauthorized creates a PostStaffUnauthorized with default headers values
func NewPostStaffUnauthorized() *PostStaffUnauthorized {
	return &PostStaffUnauthorized{}
}

/*PostStaffUnauthorized handles this case with default header values.

Unauthorized.
*/
type PostStaffUnauthorized struct {
	Payload *models_secure.Staff401Response
}

func (o *PostStaffUnauthorized) Error() string {
	return fmt.Sprintf("[POST /staff][%d] postStaffUnauthorized  %+v", 401, o.Payload)
}

func (o *PostStaffUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.Staff401Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
