package p_r_o_d_u_c_t_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProductsMultipleProductIdsSyndicatedParams creates a new GetProductsMultipleProductIdsSyndicatedParams object
// with the default values initialized.
func NewGetProductsMultipleProductIdsSyndicatedParams() *GetProductsMultipleProductIdsSyndicatedParams {
	var ()
	return &GetProductsMultipleProductIdsSyndicatedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProductsMultipleProductIdsSyndicatedParamsWithTimeout creates a new GetProductsMultipleProductIdsSyndicatedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProductsMultipleProductIdsSyndicatedParamsWithTimeout(timeout time.Duration) *GetProductsMultipleProductIdsSyndicatedParams {
	var ()
	return &GetProductsMultipleProductIdsSyndicatedParams{

		timeout: timeout,
	}
}

/*GetProductsMultipleProductIdsSyndicatedParams contains all the parameters to send to the API endpoint
for the get products multiple product ids syndicated operation typically these are written to a http.Request
*/
type GetProductsMultipleProductIdsSyndicatedParams struct {

	/*Fields
	  Fields in response. Array that lists the fields requested.

	*/
	Fields []string
	/*ProductIds
	  Comma delimited list of syndicated product IDs to fetch

	*/
	ProductIds []string

	timeout time.Duration
}

// WithFields adds the fields to the get products multiple product ids syndicated params
func (o *GetProductsMultipleProductIdsSyndicatedParams) WithFields(Fields []string) *GetProductsMultipleProductIdsSyndicatedParams {
	o.Fields = Fields
	return o
}

// WithProductIds adds the productIds to the get products multiple product ids syndicated params
func (o *GetProductsMultipleProductIdsSyndicatedParams) WithProductIds(ProductIds []string) *GetProductsMultipleProductIdsSyndicatedParams {
	o.ProductIds = ProductIds
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetProductsMultipleProductIdsSyndicatedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	valuesFields := o.Fields

	joinedFields := swag.JoinByFormat(valuesFields, "csv")
	// query array param fields
	if err := r.SetQueryParam("fields", joinedFields...); err != nil {
		return err
	}

	//valuesProductIds := o.ProductIds

	//joinedProductIds := swag.JoinByFormat(valuesProductIds, "csv")

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
