package models_core

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*CategoryUpdateBody Data to update a category.

swagger:model categoryUpdateBody
*/
type CategoryUpdateBody struct {

	/* Enabled category. Category is enabled (true) or not enabled (false).
	 */
	Enabled bool `json:"enabled,omitempty"`

	/* Parent category identifier. Identifiers to retrieve the parent category related to this category.
	 */
	ParentID int64 `json:"parent_id,omitempty"`
}

// Validate validates this category update body
func (m *CategoryUpdateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
