package models_core

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*ColorError color error

swagger:model colorError
*/
type ColorError struct {

	/* code
	 */
	Code ValidationError `json:"code,omitempty"`

	/* name
	 */
	Name ValidationError `json:"name,omitempty"`
}

// Validate validates this color error
func (m *ColorError) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
