package models_core

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Event422Error event422 error

swagger:model event422Error
*/
type Event422Error struct {

	/* A list of errors that do not apply to an attribute.
	 */
	Base ValidationError `json:"base,omitempty"`

	/* centre id
	 */
	CentreID ValidationError `json:"centre_id,omitempty"`

	/* description
	 */
	Description ValidationError `json:"description,omitempty"`

	/* disabled at
	 */
	DisabledAt ValidationError `json:"disabled_at,omitempty"`

	/* external buy url
	 */
	ExternalBuyURL ValidationError `json:"external_buy_url,omitempty"`

	/* external url
	 */
	ExternalURL ValidationError `json:"external_url,omitempty"`

	/* external url description
	 */
	ExternalURLDescription ValidationError `json:"external_url_description,omitempty"`

	/* featured
	 */
	Featured ValidationError `json:"featured,omitempty"`

	/* image ref
	 */
	ImageRef ValidationError `json:"image_ref,omitempty"`

	/* name
	 */
	Name ValidationError `json:"name,omitempty"`

	/* occurrences
	 */
	Occurrences ValidationError `json:"occurrences,omitempty"`

	/* published at
	 */
	PublishedAt ValidationError `json:"published_at,omitempty"`
}

// Validate validates this event422 error
func (m *Event422Error) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
