package models_core

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*NoticeUpdateBody Notice update parameters in message body

swagger:model noticeUpdateBody
*/
type NoticeUpdateBody struct {

	/* Attachment filename
	 */
	AttachmentRef string `json:"attachment_ref,omitempty"`

	/* Centre identifier
	 */
	CentreID string `json:"centre_id,omitempty"`

	/* Notice content text

	Min Length: 2
	*/
	Detail string `json:"detail,omitempty"`

	/* Notice expiry date
	 */
	ExpiresAt strfmt.DateTime `json:"expires_at,omitempty"`

	/* Notice is featured (true/false)
	 */
	Featured bool `json:"featured,omitempty"`

	/* Image filename
	 */
	ImageRef string `json:"image_ref,omitempty"`

	/* Image alternative text
	 */
	ImgAltText string `json:"img_alt_text,omitempty"`

	/* Notice name

	Max Length: 40
	Min Length: 2
	*/
	Name string `json:"name,omitempty"`

	/* Notice publication date
	 */
	PublishedAt strfmt.DateTime `json:"published_at,omitempty"`

	/* salience

	Maximum: 100
	Minimum: 0
	*/
	Salience *int64 `json:"salience,omitempty"`

	/* Type
	 */
	Type string `json:"type,omitempty"`
}

// Validate validates this notice update body
func (m *NoticeUpdateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDetail(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSalience(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NoticeUpdateBody) validateDetail(formats strfmt.Registry) error {

	if swag.IsZero(m.Detail) { // not required
		return nil
	}

	if err := validate.MinLength("detail", "body", string(m.Detail), 2); err != nil {
		return err
	}

	return nil
}

func (m *NoticeUpdateBody) validateName(formats strfmt.Registry) error {

	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.MinLength("name", "body", string(m.Name), 2); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", string(m.Name), 40); err != nil {
		return err
	}

	return nil
}

func (m *NoticeUpdateBody) validateSalience(formats strfmt.Registry) error {

	if swag.IsZero(m.Salience) { // not required
		return nil
	}

	if err := validate.MinimumInt("salience", "body", int64(*m.Salience), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("salience", "body", int64(*m.Salience), 100, false); err != nil {
		return err
	}

	return nil
}

var noticeUpdateBodyTypeTypePropEnum []interface{}

// prop value enum
func (m *NoticeUpdateBody) validateTypeEnum(path, location string, value string) error {
	if noticeUpdateBodyTypeTypePropEnum == nil {
		var res []string
		if err := json.Unmarshal([]byte(`["standard","emergency"]`), &res); err != nil {
			return err
		}
		for _, v := range res {
			noticeUpdateBodyTypeTypePropEnum = append(noticeUpdateBodyTypeTypePropEnum, v)
		}
	}
	if err := validate.Enum(path, location, value, noticeUpdateBodyTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *NoticeUpdateBody) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}
