package models_core

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Notice422Error notice422 error

swagger:model notice422Error
*/
type Notice422Error struct {

	/* A list of errors that do not apply to an attribute.
	 */
	Base ValidationError `json:"base,omitempty"`

	/* centre id
	 */
	CentreID ValidationError `json:"centre_id,omitempty"`

	/* detail
	 */
	Detail ValidationError `json:"detail,omitempty"`

	/* expires at
	 */
	ExpiresAt ValidationError `json:"expires_at,omitempty"`

	/* image ref
	 */
	ImageRef ValidationError `json:"image_ref,omitempty"`

	/* img alt text
	 */
	ImgAltText ValidationError `json:"img_alt_text,omitempty"`

	/* name
	 */
	Name ValidationError `json:"name,omitempty"`

	/* published at
	 */
	PublishedAt ValidationError `json:"published_at,omitempty"`
}

// Validate validates this notice422 error
func (m *Notice422Error) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
