package models_core

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*ServiceLocationBody Service locations

swagger:model serviceLocationBody
*/
type ServiceLocationBody struct {

	/* Name of this specific location
	 */
	Label string `json:"label,omitempty"`

	/* Type of location
	 */
	Name string `json:"name,omitempty"`

	/* Order in which this location should be displayed
	 */
	SortOrder int64 `json:"sort_order,omitempty"`

	/* The value of the location
	 */
	Value string `json:"value,omitempty"`
}

// Validate validates this service location body
func (m *ServiceLocationBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
