package models_core

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*TariffInstance tariff instance

swagger:model tariffInstance
*/
type TariffInstance struct {

	/* Tariff identifier.

	Required: true
	*/
	TariffCode *int64 `json:"tariff_code"`

	/* Tariff name.

	Required: true
	*/
	TariffName *string `json:"tariff_name"`
}

// Validate validates this tariff instance
func (m *TariffInstance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTariffCode(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTariffName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TariffInstance) validateTariffCode(formats strfmt.Registry) error {

	if err := validate.Required("tariff_code", "body", m.TariffCode); err != nil {
		return err
	}

	return nil
}

func (m *TariffInstance) validateTariffName(formats strfmt.Registry) error {

	if err := validate.Required("tariff_name", "body", m.TariffName); err != nil {
		return err
	}

	return nil
}
