package models_core

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*VariantPrice Product Variant Price

swagger:model variantPrice
*/
type VariantPrice struct {

	/* Variant amount, in cents
	 */
	Amount int64 `json:"amount,omitempty"`

	/* Discounted flag
	 */
	IsDiscounted bool `json:"is_discounted,omitempty"`

	/* Variant rrp, in cents
	 */
	Rrp int64 `json:"rrp,omitempty"`
}

// Validate validates this variant price
func (m *VariantPrice) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
