package c_e_n_t_r_e_e_v_e_n_t_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEventsEventIDParams creates a new GetEventsEventIDParams object
// with the default values initialized.
func NewGetEventsEventIDParams() *GetEventsEventIDParams {
	var ()
	return &GetEventsEventIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEventsEventIDParamsWithTimeout creates a new GetEventsEventIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEventsEventIDParamsWithTimeout(timeout time.Duration) *GetEventsEventIDParams {
	var ()
	return &GetEventsEventIDParams{

		timeout: timeout,
	}
}

/*GetEventsEventIDParams contains all the parameters to send to the API endpoint
for the get events event ID operation typically these are written to a http.Request
*/
type GetEventsEventIDParams struct {

	/*EventID
	  Event identifier. Request the event with event_id.

	*/
	EventID int64
	/*Fields
	  Fields in response. Array that lists the fields requested. If empty or not supplied, all attributes will be returned.

	*/
	Fields []string

	timeout time.Duration
}

// WithEventID adds the eventId to the get events event ID params
func (o *GetEventsEventIDParams) WithEventID(EventID int64) *GetEventsEventIDParams {
	o.EventID = EventID
	return o
}

// WithFields adds the fields to the get events event ID params
func (o *GetEventsEventIDParams) WithFields(Fields []string) *GetEventsEventIDParams {
	o.Fields = Fields
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetEventsEventIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param event_id
	if err := r.SetPathParam("event_id", swag.FormatInt64(o.EventID)); err != nil {
		return err
	}

	valuesFields := o.Fields

	joinedFields := swag.JoinByFormat(valuesFields, "csv")
	// query array param fields
	if err := r.SetQueryParam("fields", joinedFields...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
