package p_e_o_p_l_e_c_o_n_s_u_m_e_r

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_secure"
)

// DeleteAccountVehiclesLicensePlateReader is a Reader for the DeleteAccountVehiclesLicensePlate structure.
type DeleteAccountVehiclesLicensePlateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteAccountVehiclesLicensePlateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteAccountVehiclesLicensePlateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteAccountVehiclesLicensePlateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteAccountVehiclesLicensePlateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 423:
		result := NewDeleteAccountVehiclesLicensePlateLocked()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAccountVehiclesLicensePlateNoContent creates a DeleteAccountVehiclesLicensePlateNoContent with default headers values
func NewDeleteAccountVehiclesLicensePlateNoContent() *DeleteAccountVehiclesLicensePlateNoContent {
	return &DeleteAccountVehiclesLicensePlateNoContent{}
}

/*DeleteAccountVehiclesLicensePlateNoContent handles this case with default header values.

Successfully deleted the vehicle.
*/
type DeleteAccountVehiclesLicensePlateNoContent struct {
}

func (o *DeleteAccountVehiclesLicensePlateNoContent) Error() string {
	return fmt.Sprintf("[DELETE /account/vehicles/{license_plate}][%d] deleteAccountVehiclesLicensePlateNoContent ", 204)
}

func (o *DeleteAccountVehiclesLicensePlateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAccountVehiclesLicensePlateUnauthorized creates a DeleteAccountVehiclesLicensePlateUnauthorized with default headers values
func NewDeleteAccountVehiclesLicensePlateUnauthorized() *DeleteAccountVehiclesLicensePlateUnauthorized {
	return &DeleteAccountVehiclesLicensePlateUnauthorized{}
}

/*DeleteAccountVehiclesLicensePlateUnauthorized handles this case with default header values.

Unauthorized request.
*/
type DeleteAccountVehiclesLicensePlateUnauthorized struct {
	Payload *models_secure.UnauthorizedResponse
}

func (o *DeleteAccountVehiclesLicensePlateUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /account/vehicles/{license_plate}][%d] deleteAccountVehiclesLicensePlateUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteAccountVehiclesLicensePlateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.UnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccountVehiclesLicensePlateNotFound creates a DeleteAccountVehiclesLicensePlateNotFound with default headers values
func NewDeleteAccountVehiclesLicensePlateNotFound() *DeleteAccountVehiclesLicensePlateNotFound {
	return &DeleteAccountVehiclesLicensePlateNotFound{}
}

/*DeleteAccountVehiclesLicensePlateNotFound handles this case with default header values.

Vehicle not found.
*/
type DeleteAccountVehiclesLicensePlateNotFound struct {
	Payload *models_secure.Http404Response
}

func (o *DeleteAccountVehiclesLicensePlateNotFound) Error() string {
	return fmt.Sprintf("[DELETE /account/vehicles/{license_plate}][%d] deleteAccountVehiclesLicensePlateNotFound  %+v", 404, o.Payload)
}

func (o *DeleteAccountVehiclesLicensePlateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.Http404Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccountVehiclesLicensePlateLocked creates a DeleteAccountVehiclesLicensePlateLocked with default headers values
func NewDeleteAccountVehiclesLicensePlateLocked() *DeleteAccountVehiclesLicensePlateLocked {
	return &DeleteAccountVehiclesLicensePlateLocked{}
}

/*DeleteAccountVehiclesLicensePlateLocked handles this case with default header values.

Resource not deleted because it's locked.
*/
type DeleteAccountVehiclesLicensePlateLocked struct {
}

func (o *DeleteAccountVehiclesLicensePlateLocked) Error() string {
	return fmt.Sprintf("[DELETE /account/vehicles/{license_plate}][%d] deleteAccountVehiclesLicensePlateLocked ", 423)
}

func (o *DeleteAccountVehiclesLicensePlateLocked) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
