package p_e_o_p_l_e_c_o_n_s_u_m_e_r

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_secure"
)

// DeleteAccountCreditCardsPaymentMethodTokenReader is a Reader for the DeleteAccountCreditCardsPaymentMethodToken structure.
type DeleteAccountCreditCardsPaymentMethodTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteAccountCreditCardsPaymentMethodTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteAccountCreditCardsPaymentMethodTokenNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteAccountCreditCardsPaymentMethodTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteAccountCreditCardsPaymentMethodTokenNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 423:
		result := NewDeleteAccountCreditCardsPaymentMethodTokenLocked()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAccountCreditCardsPaymentMethodTokenNoContent creates a DeleteAccountCreditCardsPaymentMethodTokenNoContent with default headers values
func NewDeleteAccountCreditCardsPaymentMethodTokenNoContent() *DeleteAccountCreditCardsPaymentMethodTokenNoContent {
	return &DeleteAccountCreditCardsPaymentMethodTokenNoContent{}
}

/*DeleteAccountCreditCardsPaymentMethodTokenNoContent handles this case with default header values.

Successfully deleted the credit card.
*/
type DeleteAccountCreditCardsPaymentMethodTokenNoContent struct {
}

func (o *DeleteAccountCreditCardsPaymentMethodTokenNoContent) Error() string {
	return fmt.Sprintf("[DELETE /account/credit_cards/{payment_method_token}][%d] deleteAccountCreditCardsPaymentMethodTokenNoContent ", 204)
}

func (o *DeleteAccountCreditCardsPaymentMethodTokenNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAccountCreditCardsPaymentMethodTokenUnauthorized creates a DeleteAccountCreditCardsPaymentMethodTokenUnauthorized with default headers values
func NewDeleteAccountCreditCardsPaymentMethodTokenUnauthorized() *DeleteAccountCreditCardsPaymentMethodTokenUnauthorized {
	return &DeleteAccountCreditCardsPaymentMethodTokenUnauthorized{}
}

/*DeleteAccountCreditCardsPaymentMethodTokenUnauthorized handles this case with default header values.

Unauthorized request.
*/
type DeleteAccountCreditCardsPaymentMethodTokenUnauthorized struct {
	Payload *models_secure.UnauthorizedResponse
}

func (o *DeleteAccountCreditCardsPaymentMethodTokenUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /account/credit_cards/{payment_method_token}][%d] deleteAccountCreditCardsPaymentMethodTokenUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteAccountCreditCardsPaymentMethodTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.UnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccountCreditCardsPaymentMethodTokenNotFound creates a DeleteAccountCreditCardsPaymentMethodTokenNotFound with default headers values
func NewDeleteAccountCreditCardsPaymentMethodTokenNotFound() *DeleteAccountCreditCardsPaymentMethodTokenNotFound {
	return &DeleteAccountCreditCardsPaymentMethodTokenNotFound{}
}

/*DeleteAccountCreditCardsPaymentMethodTokenNotFound handles this case with default header values.

Credit card not found.
*/
type DeleteAccountCreditCardsPaymentMethodTokenNotFound struct {
	Payload *models_secure.Http404Response
}

func (o *DeleteAccountCreditCardsPaymentMethodTokenNotFound) Error() string {
	return fmt.Sprintf("[DELETE /account/credit_cards/{payment_method_token}][%d] deleteAccountCreditCardsPaymentMethodTokenNotFound  %+v", 404, o.Payload)
}

func (o *DeleteAccountCreditCardsPaymentMethodTokenNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.Http404Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccountCreditCardsPaymentMethodTokenLocked creates a DeleteAccountCreditCardsPaymentMethodTokenLocked with default headers values
func NewDeleteAccountCreditCardsPaymentMethodTokenLocked() *DeleteAccountCreditCardsPaymentMethodTokenLocked {
	return &DeleteAccountCreditCardsPaymentMethodTokenLocked{}
}

/*DeleteAccountCreditCardsPaymentMethodTokenLocked handles this case with default header values.

Resource not deleted because it's locked.
*/
type DeleteAccountCreditCardsPaymentMethodTokenLocked struct {
}

func (o *DeleteAccountCreditCardsPaymentMethodTokenLocked) Error() string {
	return fmt.Sprintf("[DELETE /account/credit_cards/{payment_method_token}][%d] deleteAccountCreditCardsPaymentMethodTokenLocked ", 423)
}

func (o *DeleteAccountCreditCardsPaymentMethodTokenLocked) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
