package p_e_o_p_l_e_c_o_n_s_u_m_e_r

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_secure"
)

// NewPostAccountKidsParams creates a new PostAccountKidsParams object
// with the default values initialized.
func NewPostAccountKidsParams() *PostAccountKidsParams {
	var ()
	return &PostAccountKidsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAccountKidsParamsWithTimeout creates a new PostAccountKidsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAccountKidsParamsWithTimeout(timeout time.Duration) *PostAccountKidsParams {
	var ()
	return &PostAccountKidsParams{

		timeout: timeout,
	}
}

/*PostAccountKidsParams contains all the parameters to send to the API endpoint
for the post account kids operation typically these are written to a http.Request
*/
type PostAccountKidsParams struct {

	/*AddKidsData
	  Data to add kids to account

	*/
	AddKidsData *models_secure.AddKidsRequest

	timeout time.Duration
}

// WithAddKidsData adds the addKidsData to the post account kids params
func (o *PostAccountKidsParams) WithAddKidsData(AddKidsData *models_secure.AddKidsRequest) *PostAccountKidsParams {
	o.AddKidsData = AddKidsData
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostAccountKidsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.AddKidsData == nil {
		o.AddKidsData = new(models_secure.AddKidsRequest)
	}

	if err := r.SetBodyParam(o.AddKidsData); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
