package p_e_o_p_l_e_c_o_n_s_u_m_e_r

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_secure"
)

// PutAccountAppsAppIDDevicesDeviceTokenReader is a Reader for the PutAccountAppsAppIDDevicesDeviceToken structure.
type PutAccountAppsAppIDDevicesDeviceTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PutAccountAppsAppIDDevicesDeviceTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutAccountAppsAppIDDevicesDeviceTokenNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutAccountAppsAppIDDevicesDeviceTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPutAccountAppsAppIDDevicesDeviceTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewPutAccountAppsAppIDDevicesDeviceTokenUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 423:
		result := NewPutAccountAppsAppIDDevicesDeviceTokenLocked()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAccountAppsAppIDDevicesDeviceTokenNoContent creates a PutAccountAppsAppIDDevicesDeviceTokenNoContent with default headers values
func NewPutAccountAppsAppIDDevicesDeviceTokenNoContent() *PutAccountAppsAppIDDevicesDeviceTokenNoContent {
	return &PutAccountAppsAppIDDevicesDeviceTokenNoContent{}
}

/*PutAccountAppsAppIDDevicesDeviceTokenNoContent handles this case with default header values.

Successfully created or updated the device.
*/
type PutAccountAppsAppIDDevicesDeviceTokenNoContent struct {
}

func (o *PutAccountAppsAppIDDevicesDeviceTokenNoContent) Error() string {
	return fmt.Sprintf("[PUT /account/apps/{app_id}/devices/{device_token}][%d] putAccountAppsAppIdDevicesDeviceTokenNoContent ", 204)
}

func (o *PutAccountAppsAppIDDevicesDeviceTokenNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAccountAppsAppIDDevicesDeviceTokenBadRequest creates a PutAccountAppsAppIDDevicesDeviceTokenBadRequest with default headers values
func NewPutAccountAppsAppIDDevicesDeviceTokenBadRequest() *PutAccountAppsAppIDDevicesDeviceTokenBadRequest {
	return &PutAccountAppsAppIDDevicesDeviceTokenBadRequest{}
}

/*PutAccountAppsAppIDDevicesDeviceTokenBadRequest handles this case with default header values.

Bad request
*/
type PutAccountAppsAppIDDevicesDeviceTokenBadRequest struct {
	Payload *models_secure.Person400Response
}

func (o *PutAccountAppsAppIDDevicesDeviceTokenBadRequest) Error() string {
	return fmt.Sprintf("[PUT /account/apps/{app_id}/devices/{device_token}][%d] putAccountAppsAppIdDevicesDeviceTokenBadRequest  %+v", 400, o.Payload)
}

func (o *PutAccountAppsAppIDDevicesDeviceTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.Person400Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAccountAppsAppIDDevicesDeviceTokenUnauthorized creates a PutAccountAppsAppIDDevicesDeviceTokenUnauthorized with default headers values
func NewPutAccountAppsAppIDDevicesDeviceTokenUnauthorized() *PutAccountAppsAppIDDevicesDeviceTokenUnauthorized {
	return &PutAccountAppsAppIDDevicesDeviceTokenUnauthorized{}
}

/*PutAccountAppsAppIDDevicesDeviceTokenUnauthorized handles this case with default header values.

Unauthorized
*/
type PutAccountAppsAppIDDevicesDeviceTokenUnauthorized struct {
	Payload *models_secure.UnauthorizedResponse
}

func (o *PutAccountAppsAppIDDevicesDeviceTokenUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /account/apps/{app_id}/devices/{device_token}][%d] putAccountAppsAppIdDevicesDeviceTokenUnauthorized  %+v", 401, o.Payload)
}

func (o *PutAccountAppsAppIDDevicesDeviceTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.UnauthorizedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAccountAppsAppIDDevicesDeviceTokenUnprocessableEntity creates a PutAccountAppsAppIDDevicesDeviceTokenUnprocessableEntity with default headers values
func NewPutAccountAppsAppIDDevicesDeviceTokenUnprocessableEntity() *PutAccountAppsAppIDDevicesDeviceTokenUnprocessableEntity {
	return &PutAccountAppsAppIDDevicesDeviceTokenUnprocessableEntity{}
}

/*PutAccountAppsAppIDDevicesDeviceTokenUnprocessableEntity handles this case with default header values.

Returns an array of error messages explaining the problems with the provided attributes.
*/
type PutAccountAppsAppIDDevicesDeviceTokenUnprocessableEntity struct {
	Payload *models_secure.DeviceUpsert422Response
}

func (o *PutAccountAppsAppIDDevicesDeviceTokenUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /account/apps/{app_id}/devices/{device_token}][%d] putAccountAppsAppIdDevicesDeviceTokenUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *PutAccountAppsAppIDDevicesDeviceTokenUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_secure.DeviceUpsert422Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAccountAppsAppIDDevicesDeviceTokenLocked creates a PutAccountAppsAppIDDevicesDeviceTokenLocked with default headers values
func NewPutAccountAppsAppIDDevicesDeviceTokenLocked() *PutAccountAppsAppIDDevicesDeviceTokenLocked {
	return &PutAccountAppsAppIDDevicesDeviceTokenLocked{}
}

/*PutAccountAppsAppIDDevicesDeviceTokenLocked handles this case with default header values.

Resource not updated because it's locked.
*/
type PutAccountAppsAppIDDevicesDeviceTokenLocked struct {
}

func (o *PutAccountAppsAppIDDevicesDeviceTokenLocked) Error() string {
	return fmt.Sprintf("[PUT /account/apps/{app_id}/devices/{device_token}][%d] putAccountAppsAppIdDevicesDeviceTokenLocked ", 423)
}

func (o *PutAccountAppsAppIDDevicesDeviceTokenLocked) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
