package s_t_o_r_e_i_n_f_o_r_m_a_t_i_o_n

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// NewPostStoresParams creates a new PostStoresParams object
// with the default values initialized.
func NewPostStoresParams() *PostStoresParams {
	var ()
	return &PostStoresParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostStoresParamsWithTimeout creates a new PostStoresParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostStoresParamsWithTimeout(timeout time.Duration) *PostStoresParams {
	var ()
	return &PostStoresParams{

		timeout: timeout,
	}
}

/*PostStoresParams contains all the parameters to send to the API endpoint
for the post stores operation typically these are written to a http.Request
*/
type PostStoresParams struct {

	/*Authorization
	  Staff Access token.

	*/
	Authorization string
	/*StoreData
	  Data to create a store.

	*/
	StoreData *models_core.StoreCreateBody

	timeout time.Duration
}

// WithAuthorization adds the authorization to the post stores params
func (o *PostStoresParams) WithAuthorization(Authorization string) *PostStoresParams {
	o.Authorization = Authorization
	return o
}

// WithStoreData adds the storeData to the post stores params
func (o *PostStoresParams) WithStoreData(StoreData *models_core.StoreCreateBody) *PostStoresParams {
	o.StoreData = StoreData
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostStoresParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.StoreData == nil {
		o.StoreData = new(models_core.StoreCreateBody)
	}

	if err := r.SetBodyParam(o.StoreData); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
