package k_i_o_s_k

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteKioskKioskCentresKioskCentreIDParams creates a new DeleteKioskKioskCentresKioskCentreIDParams object
// with the default values initialized.
func NewDeleteKioskKioskCentresKioskCentreIDParams() *DeleteKioskKioskCentresKioskCentreIDParams {
	var ()
	return &DeleteKioskKioskCentresKioskCentreIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteKioskKioskCentresKioskCentreIDParamsWithTimeout creates a new DeleteKioskKioskCentresKioskCentreIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteKioskKioskCentresKioskCentreIDParamsWithTimeout(timeout time.Duration) *DeleteKioskKioskCentresKioskCentreIDParams {
	var ()
	return &DeleteKioskKioskCentresKioskCentreIDParams{

		timeout: timeout,
	}
}

/*DeleteKioskKioskCentresKioskCentreIDParams contains all the parameters to send to the API endpoint
for the delete kiosk kiosk centres kiosk centre ID operation typically these are written to a http.Request
*/
type DeleteKioskKioskCentresKioskCentreIDParams struct {

	/*Authorization
	  Staff Access token.

	*/
	Authorization string
	/*KioskCentreID
	  Kiosk centre identifier. Request to delete the kioks centre with kiosk_centre_id.

	*/
	KioskCentreID int64

	timeout time.Duration
}

// WithAuthorization adds the authorization to the delete kiosk kiosk centres kiosk centre ID params
func (o *DeleteKioskKioskCentresKioskCentreIDParams) WithAuthorization(Authorization string) *DeleteKioskKioskCentresKioskCentreIDParams {
	o.Authorization = Authorization
	return o
}

// WithKioskCentreID adds the kioskCentreId to the delete kiosk kiosk centres kiosk centre ID params
func (o *DeleteKioskKioskCentresKioskCentreIDParams) WithKioskCentreID(KioskCentreID int64) *DeleteKioskKioskCentresKioskCentreIDParams {
	o.KioskCentreID = KioskCentreID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteKioskKioskCentresKioskCentreIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param kiosk_centre_id
	if err := r.SetPathParam("kiosk_centre_id", swag.FormatInt64(o.KioskCentreID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
