package k_i_o_s_k

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// GetKioskKioskCentresReader is a Reader for the GetKioskKioskCentres structure.
type GetKioskKioskCentresReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetKioskKioskCentresReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetKioskKioskCentresOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetKioskKioskCentresOK creates a GetKioskKioskCentresOK with default headers values
func NewGetKioskKioskCentresOK() *GetKioskKioskCentresOK {
	return &GetKioskKioskCentresOK{}
}

/*GetKioskKioskCentresOK handles this case with default header values.

Successfully retrieved the list of kiosk centres.
*/
type GetKioskKioskCentresOK struct {
	Payload *models_core.KioskCentreListResponse
}

func (o *GetKioskKioskCentresOK) Error() string {
	return fmt.Sprintf("[GET /kiosk/kiosk_centres][%d] getKioskKioskCentresOK  %+v", 200, o.Payload)
}

func (o *GetKioskKioskCentresOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_core.KioskCentreListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
