package k_i_o_s_k

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"restclient/models_core"
)

// NewPatchKioskKioskCentresKioskCentreIDParams creates a new PatchKioskKioskCentresKioskCentreIDParams object
// with the default values initialized.
func NewPatchKioskKioskCentresKioskCentreIDParams() *PatchKioskKioskCentresKioskCentreIDParams {
	var ()
	return &PatchKioskKioskCentresKioskCentreIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchKioskKioskCentresKioskCentreIDParamsWithTimeout creates a new PatchKioskKioskCentresKioskCentreIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchKioskKioskCentresKioskCentreIDParamsWithTimeout(timeout time.Duration) *PatchKioskKioskCentresKioskCentreIDParams {
	var ()
	return &PatchKioskKioskCentresKioskCentreIDParams{

		timeout: timeout,
	}
}

/*PatchKioskKioskCentresKioskCentreIDParams contains all the parameters to send to the API endpoint
for the patch kiosk kiosk centres kiosk centre ID operation typically these are written to a http.Request
*/
type PatchKioskKioskCentresKioskCentreIDParams struct {

	/*Authorization
	  Staff Access token.

	*/
	Authorization string
	/*CentreData
	  Data to update a kiosk centre.

	*/
	CentreData *models_core.KioskCentreUpdateBody
	/*KioskCentreID
	  Kiosk centre identifier. Request to update the kiosk centre with kiosk_centre_id.

	*/
	KioskCentreID int64

	timeout time.Duration
}

// WithAuthorization adds the authorization to the patch kiosk kiosk centres kiosk centre ID params
func (o *PatchKioskKioskCentresKioskCentreIDParams) WithAuthorization(Authorization string) *PatchKioskKioskCentresKioskCentreIDParams {
	o.Authorization = Authorization
	return o
}

// WithCentreData adds the centreData to the patch kiosk kiosk centres kiosk centre ID params
func (o *PatchKioskKioskCentresKioskCentreIDParams) WithCentreData(CentreData *models_core.KioskCentreUpdateBody) *PatchKioskKioskCentresKioskCentreIDParams {
	o.CentreData = CentreData
	return o
}

// WithKioskCentreID adds the kioskCentreId to the patch kiosk kiosk centres kiosk centre ID params
func (o *PatchKioskKioskCentresKioskCentreIDParams) WithKioskCentreID(KioskCentreID int64) *PatchKioskKioskCentresKioskCentreIDParams {
	o.KioskCentreID = KioskCentreID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PatchKioskKioskCentresKioskCentreIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.CentreData == nil {
		o.CentreData = new(models_core.KioskCentreUpdateBody)
	}

	if err := r.SetBodyParam(o.CentreData); err != nil {
		return err
	}

	// path param kiosk_centre_id
	if err := r.SetPathParam("kiosk_centre_id", swag.FormatInt64(o.KioskCentreID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
